id: P1013C20F
initial_creation_type: ocr
source_metadata:
  volumes:
    a4643c9e60f5430abfa0cecf2e9488fb:
      base_file: v075.txt
      image_group_id: I1PD95920
      title: རྣམ་གྲངས་བསྡུ་བ།
      total_pages: 1529
      volume_number: 75
