id: D22A38994
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-07T13:58:06+00:00'
last_modified: '2022-05-29T08:17:21.158471+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    81cf:
      image_group_id: I1PD95920
      title: རྣམ་གྲངས་བསྡུ་བ།
      total_pages: 1529
      order: 75
      base_file: 81cf.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
